### PR TITLE
simplify subtitle/audio script-opts

### PR DESCRIPTION
**Pull request by CogentRedTester**
Simplifies the subtitle/audio extension `script-opts`.

Pinging @dyphire for thoughts.

### CODE REVIEW

**Comment by dyphire** [comment]
No longer use the extension blacklist?

Although I was also skeptical about the necessity of the blacklist of subtitle extensions at the beginning, what is the reason for the cancellation of the blacklist of audio extensions?

**Comment by CogentRedTester** [comment]
It hasn't been cancelled. Instead of using a whitelist/blacklist we just make the script-opt the actual list of all valid extensions. So you can add any extension, or remove any of the default extensions. This wasn't possible for the main extension list because it is so long, but for subtitles and audio tracks there are so few extensions it can be done without much hassle. This way it's really clear what the defaults are as well.

**Comment by dyphire** [comment]
> It hasn't been cancelled. Instead of using a whitelist/blacklist we just make the script-opt the actual list of all valid extensions. So you can add any extension, or remove any of the default extensions. This wasn't possible for the main extension list because it is so long, but for subtitles and audio tracks there are so few extensions it can be done without much hassle. This way it's really clear what the defaults are as well.

You are right. Users can choose to use automatic configuration to modify the relevant extension list, which is the same as the previous blacklist list.

**Comment by CogentRedTester** [comment]
Do you have any objections to me changing it to this? I think it's simpler and neater.

**Comment by dyphire** [comment]
> Do you have any objections to me changing it to this? I think it's simpler and neater.

I also think this change looks good.

**Pull request merged**
