### PR TITLE
change file-browser to directory script and bump min mpv version to v0.33

### PR DESCRIPTION
**Pull request by CogentRedTester**
This PR aims to restructure file-browser into a directory script (see [this section](https://mpv.io/manual/master/#script-location) of the mpv manual). The main advantage of this change is to break up the code into smaller, more manageable files. Currently file-browser is exactly 2300 lines long, and it is becoming increasingly difficult to navigate the code.

This is a major restructuring that will result in the relocation of the vast majority of the code. 

Changing file-browser to a directory script will also require bumping the minimum supported version of mpv to v0.33. I have been hesitant to increase the minimum version in the past, but v0.33 released just over three years ago now, so I think I've given people enough time to update. I'd be willing to bump the version number higher, but I don't see any new features that are really worth using in the base script except for the `user-data` property, and that was only added in v0.36 six months ago, which I consider a little too recent.

To do list:

- [x] Move options to module
- [x] Move global variables to module
- [x] Move utility functions to module
- [x] Move ass drawing code to module
- [x] Move caching code to module
- [x] Move in-built parsers to modules
- [x] Move directory navigation to module
- [x] Move directory parsing to module
- [x] Move addon API and setup to module
- [x] Move keybind setup and execution to module
- [x] Move playlist appending to module
- [x] Try and leave only environment setup, setup function calls, and mpv callbacks in main file
- [x] Update documentation with new install instructions and bumped version requirement
- [x] Make and document unsupported branch that contains the last version of the v0.31 compatible code

### CODE REVIEW

**Comment by CogentRedTester** [comment]
With the latest commit all of the code has now been moved into modules, and the `main.lua` file has been made significantly tidier. There are still some refactoring and stylistic changes I would like to do, however this PR is getting very beefy, and I have other changes I'd like to make that are waiting on this.

The important thing is that all of the code has been moved over to modules with relatively few changes, and everything is (hopefully) working. As such I think it is satisfactory to merge with the code in the current state. The only thing to do first is to update the README with the new install instructions.

One thing to note is that this PR will actually break a couple of scripts using undocumented features of the API, specifically it will likely break [windows-sort](https://github.com/CogentRedTester/mpv-file-browser/issues/99#issuecomment-1829221378) and [filter-recyclebin](https://github.com/CogentRedTester/mpv-file-browser/issues/52#issuecomment-1120615541). On the other hand the new modules may make it easier to do what they are doing.

**Comment by CogentRedTester** [comment]
@dyphire perhaps you'd like to take it for a spin before I merge? Might be nice to have an extra person confirm I haven't fundamentally broken something. 😅

**Comment by dyphire** [comment]
> @dyphire perhaps you'd like to take it for a spin before I merge? Might be nice to have an extra person confirm I haven't fundamentally broken something. 😅

Except for the script mentioned in https://github.com/CogentRedTester/mpv-file-browser/issues/99#issuecomment-1829221378 which is no longer available, everything else LGTM.

**Comment by CogentRedTester** [comment]
@dyphire I believe that changing that addon to the following should work. Unfortunately I'm not on windows so I can't confirm, can you try running it:

```lua
local fb_utils = require 'modules.utils'

-- this code is based on https://github.com/mpvnet-player/mpv.net/issues/575#issuecomment-1817413401
local ffi = require "ffi"
local winapi = {
        ffi = ffi,
        C = ffi.C,
        CP_UTF8 = 65001,
        shlwapi = ffi.load("shlwapi"),
    }

-- ffi code from https://github.com/po5/thumbfast, Mozilla Public License Version 2.0
ffi.cdef[[
    int __stdcall MultiByteToWideChar(unsigned int CodePage, unsigned long dwFlags, const char *lpMultiByteStr,
    int cbMultiByte, wchar_t *lpWideCharStr, int cchWideChar);
    int __stdcall StrCmpLogicalW(wchar_t *psz1, wchar_t *psz2);
]]

winapi.utf8_to_wide = function(utf8_str)
    if utf8_str then
        local utf16_len = winapi.C.MultiByteToWideChar(winapi.CP_UTF8, 0, utf8_str, -1, nil, 0)

        if utf16_len > 0 then
            local utf16_str = winapi.ffi.new("wchar_t[?]", utf16_len)

            if winapi.C.MultiByteToWideChar(winapi.CP_UTF8, 0, utf8_str, -1, utf16_str, utf16_len) > 0 then
                return utf16_str
            end
        end
    end

    return ""
end

fb_utils.sort = function (t)
    table.sort(t, function(a, b)
        local a_wide = winapi.utf8_to_wide(a.type:sub(1, 1) .. (a.label or a.name))
        local b_wide = winapi.utf8_to_wide(b.type:sub(1, 1) .. (b.label or b.name))
        return winapi.shlwapi.StrCmpLogicalW(a_wide, b_wide) == -1
    end)

    return t
end

return { version = '1.1.0' }
```

If you can confirm it's working then I'll merge and update those two addons. This is what you get when I write people addons using internal undocumented features 😅 (still better than adding all this bloat directly, however).

**Comment by dyphire** [comment]
> If you can confirm it's working then I'll merge and update those two addons. This is what you get when I write people addons using internal undocumented features 😅 (still better than adding all this bloat directly, however).

Yes, it works.

**Pull request merged**
